#!/bin/sh

if [ "$1" = "ini" ]; then
  echo "Using php.ini to set include_path"
  docker run --rm -v $PWD:/app --workdir /app --entrypoint php ghcr.io/phpstan/phpstan -c /app/php.ini /composer/vendor/bin/phpstan analyse
else
  echo "Using bootstrap file to set include_path"
  docker run --rm -v $PWD:/app --workdir /app ghcr.io/phpstan/phpstan analyse --autoload-file /app/phpstan-bootstrap.php
fi
